import Head from 'next/head'
import { Inter } from 'next/font/google'
import LoginAuth from '../components/login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <div className='d-flex justify-content-between p-4 m-4'>
      <Head>
        <title>Wealth Spring | Login </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='d-flex justify-content-between ms-5 mt-5 text-center'>
        <h1 className='text-center'>Welcome to Wealth Spring!</h1>
      </div>
      <div className='p-4 me-5'>
        <LoginAuth />
      </div>
    </div>
  )
}
